name = "PrecompileSignatures"
uuid = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"
authors = ["Rik Huijzer <t.h.huijzer@rug.nl>"]
version = "1.0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Documenter = "0.27"
Scratch = "1.1"
julia = "1.6"

[extras]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pluto", "Test"]
